/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BenefitCard: typeof import('./src/components/ui/BenefitCard.vue')['default']
    BenifetSection: typeof import('./src/components/sections/BenifetSection.vue')['default']
    BundleCard: typeof import('./src/components/ui/BundleCard.vue')['default']
    CategoriesSection: typeof import('./src/components/sections/CategoriesSection.vue')['default']
    CategoryCard: typeof import('./src/components/ui/CategoryCard.vue')['default']
    CircularText: typeof import('./src/components/ui/CircularText.vue')['default']
    CourseCard: typeof import('./src/components/ui/CourseCard.vue')['default']
    CourseSection: typeof import('./src/components/sections/CourseSection.vue')['default']
    ExclusiveBundlesSection: typeof import('./src/components/sections/ExclusiveBundlesSection.vue')['default']
    FooterSection: typeof import('./src/components/sections/FooterSection.vue')['default']
    GiftCardsSection: typeof import('./src/components/sections/GiftCardsSection.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    Navigation: typeof import('./src/components/ui/Navigation.vue')['default']
    SectionTitle: typeof import('./src/components/ui/SectionTitle.vue')['default']
  }
}
